server:
  port: 8000

spring:
  application:
    name: textshare-cleanup
  data:
    redis:
      host: localhost
      port: 6380
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:1111}

minio:
  url: http://localhost:9000 #todo
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin123}
  bucket-name: ${MINIO_BUCKET:textshare-notes}

cleanup:
  interval-minutes: 10
  batch-size: 100
  enabled: true

logging:
  level:
    dev.textshare.cleanup: DEBUG